//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Сессия__1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Телком_Нема_СвязьEntities : DbContext
    {
        private static Телком_Нема_СвязьEntities _context;
        public Телком_Нема_СвязьEntities()
            : base("name=Телком_Нема_СвязьEntities")
        {
        }

    public static Телком_Нема_СвязьEntities GetContext() 
        {
            if ( _context == null)
            _context = new Телком_Нема_СвязьEntities();

            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Данные_по_оборудованию> Данные_по_оборудованию { get; set; }
        public virtual DbSet<Данные_по_подключению_абонентов> Данные_по_подключению_абонентов { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<Тип_оборудования> Тип_оборудования { get; set; }
        public virtual DbSet<Тип_порта> Тип_порта { get; set; }
    }
}
