//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Сессия__1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        public int ID_пользователя { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public string Отчество { get; set; }
        public string Номер { get; set; }
        public string Пароль { get; set; }
        public string Почта { get; set; }
        public string Номер_телефона { get; set; }
        public Nullable<int> Роль { get; set; }
    
        public virtual Роли Роли { get; set; }
    }
}
