//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Сессия__1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Тип_порта
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Тип_порта()
        {
            this.Данные_по_подключению_абонентов = new HashSet<Данные_по_подключению_абонентов>();
        }
    
        public int ID_типа_порта { get; set; }
        public string Тип_порта1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Данные_по_подключению_абонентов> Данные_по_подключению_абонентов { get; set; }
    }
}
